services:
  dcx:
    container_name: dcx
    image: rlproto/picture_pck:picture_pck-v1.0  # Use the existing 'picture' image from Docker Hub
    network_mode: bridge
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/picture_dcx:/app/data
    environment:
      OPC_SERVER_URL: "opc.tcp://10.15.160.150:49350"
      TAG_NAME : "ns=2;s=Simulator.simulator.teste_sodavision"
      #TAG_NAME: "ns=2;s=SODA_TEMPLATE.FILTRACAO.RASP_PASSO"
      STATUS_TAG : "ns=2;s=DCX501001.PLC.Status_CA"
      CAMERA_INDEX: "0"
      EQUIPMENT: "dcx"
      VALID_STEPS: "1;0;1"
      NUMBER_OF_PICTURES: "3"
      ENABLE_DUMP : True

    command: ["python", "app.py"]
volumes:
  cozinhador: